from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

SCHEMA = "aurum-pi4-single-driver-candidate-v1"
ALLOWED_TARGETS = {
    "gpio-leds": {
        "compatible": "gpio-leds",
        "candidate_driver": "aurum-gpio-leds",
        "working_driver_aliases": {"gpio-leds", "leds-gpio"},
        "safety_class": "noncritical-indicator",
    }
}


def _c_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _generation_1_source(compatible: str, driver_name: str) -> str:
    return f'''// Generated by Aurum bounded Pi4 driver synthesis.\n// Generation 1 proves exact-device ownership and rollback only.\n#include <linux/module.h>\n#include <linux/platform_device.h>\n#include <linux/of.h>\n\nstatic int aurum_probe(struct platform_device *pdev)\n{{\n    dev_info(&pdev->dev, "Aurum generation-1 candidate bound\\n");\n    return 0;\n}}\n\nstatic const struct of_device_id aurum_of_match[] = {{\n    {{ .compatible = "{_c_string(compatible)}" }},\n    {{ }}\n}};\nMODULE_DEVICE_TABLE(of, aurum_of_match);\n\nstatic struct platform_driver aurum_driver = {{\n    .probe = aurum_probe,\n    .driver = {{\n        .name = "{_c_string(driver_name)}",\n        .of_match_table = aurum_of_match,\n    }},\n}};\n\nmodule_platform_driver(aurum_driver);\nMODULE_LICENSE("GPL");\nMODULE_AUTHOR("Aurum");\nMODULE_DESCRIPTION("Aurum Pi4 gpio-leds exact-observation candidate generation 1");\n'''


def _generation_2_source(compatible: str, driver_name: str) -> str:
    return f'''// Generated by Aurum bounded Pi4 driver synthesis.\n// Generation 2 implements bounded GPIO LED on/off behavior through gpiolib.\n#include <linux/device.h>\n#include <linux/err.h>\n#include <linux/gpio/consumer.h>\n#include <linux/leds.h>\n#include <linux/module.h>\n#include <linux/platform_device.h>\n#include <linux/property.h>\n#include <linux/slab.h>\n\nstruct aurum_led {{\n    struct led_classdev cdev;\n    struct gpio_desc *gpiod;\n}};\n\nstruct aurum_leds {{\n    int count;\n    struct aurum_led *leds;\n}};\n\nstatic int aurum_led_set(struct led_classdev *cdev, enum led_brightness value)\n{{\n    struct aurum_led *led = container_of(cdev, struct aurum_led, cdev);\n    gpiod_set_value_cansleep(led->gpiod, value == LED_OFF ? 0 : 1);\n    return 0;\n}}\n\nstatic int aurum_probe(struct platform_device *pdev)\n{{\n    struct device *dev = &pdev->dev;\n    struct fwnode_handle *child;\n    struct aurum_leds *priv;\n    int count = device_get_child_node_count(dev);\n    int used = 0;\n\n    if (count <= 0)\n        return -ENODEV;\n\n    priv = devm_kzalloc(dev, sizeof(*priv), GFP_KERNEL);\n    if (!priv)\n        return -ENOMEM;\n    priv->leds = devm_kcalloc(dev, count, sizeof(*priv->leds), GFP_KERNEL);\n    if (!priv->leds)\n        return -ENOMEM;\n\n    device_for_each_child_node(dev, child) {{\n        struct aurum_led *led = &priv->leds[used];\n        struct led_init_data init_data = {{ .fwnode = child }};\n        int state;\n        int ret;\n\n        led->gpiod = devm_fwnode_gpiod_get(dev, child, NULL, GPIOD_ASIS, NULL);\n        if (IS_ERR(led->gpiod)) {{\n            ret = PTR_ERR(led->gpiod);\n            fwnode_handle_put(child);\n            return dev_err_probe(dev, ret, "Aurum could not acquire LED GPIO\\n");\n        }}\n\n        state = gpiod_get_value_cansleep(led->gpiod);\n        if (state < 0) {{\n            fwnode_handle_put(child);\n            return state;\n        }}\n        ret = gpiod_direction_output(led->gpiod, state ? 1 : 0);\n        if (ret) {{\n            fwnode_handle_put(child);\n            return ret;\n        }}\n\n        led->cdev.max_brightness = 1;\n        led->cdev.brightness = state ? 1 : 0;\n        led->cdev.brightness_set_blocking = aurum_led_set;\n        ret = devm_led_classdev_register_ext(dev, &led->cdev, &init_data);\n        if (ret) {{\n            fwnode_handle_put(child);\n            return ret;\n        }}\n        used++;\n    }}\n\n    priv->count = used;\n    platform_set_drvdata(pdev, priv);\n    dev_info(dev, "Aurum generation-2 LED driver active leds=%d\\n", used);\n    return used ? 0 : -ENODEV;\n}}\n\nstatic const struct of_device_id aurum_of_match[] = {{\n    {{ .compatible = "{_c_string(compatible)}" }},\n    {{ }}\n}};\nMODULE_DEVICE_TABLE(of, aurum_of_match);\n\nstatic struct platform_driver aurum_driver = {{\n    .probe = aurum_probe,\n    .driver = {{\n        .name = "{_c_string(driver_name)}",\n        .of_match_table = aurum_of_match,\n    }},\n}};\n\nmodule_platform_driver(aurum_driver);\nMODULE_LICENSE("GPL");\nMODULE_AUTHOR("Aurum");\nMODULE_DESCRIPTION("Aurum Pi4 gpio-leds bounded functional candidate generation 2");\n'''


def synthesize(evidence: dict, out_dir: Path, generation: int = 1) -> dict:
    target = str(evidence.get("target", ""))
    if target not in ALLOWED_TARGETS:
        raise ValueError(f"unsupported bounded target: {target}")
    if generation not in {1, 2}:
        raise ValueError(f"unsupported generation: {generation}")
    policy = ALLOWED_TARGETS[target]
    compatible = str(evidence.get("compatible", ""))
    if compatible != policy["compatible"]:
        raise ValueError(f"compatible mismatch: {compatible!r}")
    working_driver = str(evidence.get("working_driver", ""))
    if working_driver not in policy["working_driver_aliases"]:
        raise ValueError(f"unexpected working driver: {working_driver!r}")
    device = str(evidence.get("device", "")).strip()
    kernel = str(evidence.get("kernel", "")).strip()
    model = str(evidence.get("model", "")).strip()
    if not device or not kernel or "Raspberry Pi 4" not in model:
        raise ValueError("incomplete exact-hardware evidence")

    driver_name = policy["candidate_driver"]
    source = (
        _generation_1_source(compatible, driver_name)
        if generation == 1
        else _generation_2_source(compatible, driver_name)
    )
    module_stem = driver_name.replace("-", "_")
    makefile = f"obj-m += {module_stem}.o\n"

    out_dir.mkdir(parents=True, exist_ok=True)
    source_path = out_dir / f"{module_stem}.c"
    makefile_path = out_dir / "Makefile"
    source_path.write_text(source, encoding="utf-8")
    makefile_path.write_text(makefile, encoding="utf-8")

    digest = hashlib.sha256(source.encode("utf-8")).hexdigest()
    manifest = {
        "schema": SCHEMA,
        "target": target,
        "candidate_driver": driver_name,
        "module_stem": module_stem,
        "compatible": compatible,
        "observed_device": device,
        "observed_kernel": kernel,
        "observed_model": model,
        "observed_working_driver": working_driver,
        "safety_class": policy["safety_class"],
        "generation": generation,
        "capability": (
            "platform-device ownership/probe only"
            if generation == 1
            else "bounded GPIO LED class and on/off behavior"
        ),
        "physical_led_writes": generation >= 2,
        "raw_mmio_writes": False,
        "firmware_changes": False,
        "network_changes": False,
        "storage_changes": False,
        "source_sha256": digest,
        "rollback_required": True,
    }
    (out_dir / "candidate-manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--evidence", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--generation", type=int, default=1)
    args = parser.parse_args()
    evidence = json.loads(Path(args.evidence).read_text(encoding="utf-8"))
    manifest = synthesize(evidence, Path(args.out), generation=args.generation)
    print(json.dumps(manifest, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
