from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

SCHEMA = "aurum-pi4-single-driver-candidate-v1"
ALLOWED_TARGETS = {
    "gpio-leds": {
        "compatible": "gpio-leds",
        "candidate_driver": "aurum-gpio-leds",
        "safety_class": "noncritical-indicator",
    }
}


def _c_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def synthesize(evidence: dict, out_dir: Path) -> dict:
    target = str(evidence.get("target", ""))
    if target not in ALLOWED_TARGETS:
        raise ValueError(f"unsupported bounded target: {target}")
    policy = ALLOWED_TARGETS[target]
    compatible = str(evidence.get("compatible", ""))
    if compatible != policy["compatible"]:
        raise ValueError(f"compatible mismatch: {compatible!r}")
    if evidence.get("working_driver") != target:
        raise ValueError("working driver evidence does not match target")
    device = str(evidence.get("device", "")).strip()
    kernel = str(evidence.get("kernel", "")).strip()
    model = str(evidence.get("model", "")).strip()
    if not device or not kernel or "Raspberry Pi 4" not in model:
        raise ValueError("incomplete exact-hardware evidence")

    driver_name = policy["candidate_driver"]
    source = f'''// Generated by Aurum bounded Pi4 driver synthesis.\n// Candidate intentionally implements ownership/probe only in generation 1.\n#include <linux/module.h>\n#include <linux/platform_device.h>\n#include <linux/of.h>\n\nstatic int aurum_probe(struct platform_device *pdev)\n{{\n    dev_info(&pdev->dev, "Aurum candidate driver bound to exact observed device\\n");\n    return 0;\n}}\n\nstatic const struct of_device_id aurum_of_match[] = {{\n    {{ .compatible = "{_c_string(compatible)}" }},\n    {{ }}\n}};\nMODULE_DEVICE_TABLE(of, aurum_of_match);\n\nstatic struct platform_driver aurum_driver = {{\n    .probe = aurum_probe,\n    .driver = {{\n        .name = "{_c_string(driver_name)}",\n        .of_match_table = aurum_of_match,\n    }},\n}};\n\nmodule_platform_driver(aurum_driver);\nMODULE_LICENSE("GPL");\nMODULE_AUTHOR("Aurum");\nMODULE_DESCRIPTION("Aurum Pi4 gpio-leds exact-observation candidate generation 1");\n'''
    makefile = f"obj-m += {driver_name.replace('-', '_')}.o\n"
    module_stem = driver_name.replace("-", "_")

    out_dir.mkdir(parents=True, exist_ok=True)
    source_path = out_dir / f"{module_stem}.c"
    makefile_path = out_dir / "Makefile"
    source_path.write_text(source, encoding="utf-8")
    makefile_path.write_text(makefile, encoding="utf-8")

    digest = hashlib.sha256(source.encode("utf-8")).hexdigest()
    manifest = {
        "schema": SCHEMA,
        "target": target,
        "candidate_driver": driver_name,
        "module_stem": module_stem,
        "compatible": compatible,
        "observed_device": device,
        "observed_kernel": kernel,
        "observed_model": model,
        "safety_class": policy["safety_class"],
        "generation": 1,
        "capability": "platform-device ownership/probe only",
        "physical_writes": False,
        "firmware_changes": False,
        "network_changes": False,
        "storage_changes": False,
        "source_sha256": digest,
        "rollback_required": True,
    }
    (out_dir / "candidate-manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--evidence", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    evidence = json.loads(Path(args.evidence).read_text(encoding="utf-8"))
    manifest = synthesize(evidence, Path(args.out))
    print(json.dumps(manifest, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
