from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

SCHEMA = "aurum-pi4-single-driver-candidate-v1"
ALLOWED_TARGETS = {
    "gpio-leds": {
        "compatible": "gpio-leds",
        "candidate_driver": "aurum-gpio-leds",
        "working_driver_aliases": {"gpio-leds", "leds-gpio"},
        "safety_class": "noncritical-indicator",
    }
}


def _c_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _generation_1_source(compatible: str, driver_name: str) -> str:
    return f'''// Generated by Aurum bounded Pi4 driver synthesis.\n// Generation 1 proves exact-device ownership and rollback only.\n#include <linux/module.h>\n#include <linux/platform_device.h>\n#include <linux/of.h>\n\nstatic int aurum_probe(struct platform_device *pdev)\n{{\n    dev_info(&pdev->dev, "Aurum generation-1 candidate bound\\n");\n    return 0;\n}}\n\nstatic const struct of_device_id aurum_of_match[] = {{\n    {{ .compatible = "{_c_string(compatible)}" }},\n    {{ }}\n}};\nMODULE_DEVICE_TABLE(of, aurum_of_match);\n\nstatic struct platform_driver aurum_driver = {{\n    .probe = aurum_probe,\n    .driver = {{\n        .name = "{_c_string(driver_name)}",\n        .of_match_table = aurum_of_match,\n    }},\n}};\n\nmodule_platform_driver(aurum_driver);\nMODULE_LICENSE("GPL");\nMODULE_AUTHOR("Aurum");\nMODULE_DESCRIPTION("Aurum Pi4 gpio-leds exact-observation candidate generation 1");\n'''


def _functional_source(compatible: str, driver_name: str, generation: int) -> str:
    if generation == 2:
        struct_extra = ""
        set_functions = '''static int aurum_led_set(struct led_classdev *cdev, enum led_brightness value)
{
    struct aurum_led *led = container_of(cdev, struct aurum_led, cdev);
    gpiod_set_value_cansleep(led->gpiod, value == LED_OFF ? 0 : 1);
    return 0;
}
'''
        callback_setup = '''        led->cdev.brightness_set_blocking = aurum_led_set;'''
        capability_comment = "bounded GPIO LED behavior and learned Pi readback semantics"
    elif generation in {3, 4, 5, 6}:
        struct_extra = "    bool can_sleep;\n"
        set_functions = '''static void aurum_led_set(struct led_classdev *cdev, enum led_brightness value)
{
    struct aurum_led *led = container_of(cdev, struct aurum_led, cdev);
    gpiod_set_value(led->gpiod, value == LED_OFF ? 0 : 1);
}

static int aurum_led_set_blocking(struct led_classdev *cdev, enum led_brightness value)
{
    struct aurum_led *led = container_of(cdev, struct aurum_led, cdev);
    gpiod_set_value_cansleep(led->gpiod, value == LED_OFF ? 0 : 1);
    return 0;
}
'''
        callback_setup = '''        led->can_sleep = gpiod_cansleep(led->gpiod);
        if (led->can_sleep)
            led->cdev.brightness_set_blocking = aurum_led_set_blocking;
        else
            led->cdev.brightness_set = aurum_led_set;'''
        capability_comment = {
            3: "reference-aligned sleep-aware GPIO LED writes plus learned Pi readback semantics",
            4: "reference-aligned default-state initialization, sleep-aware GPIO LED writes, and learned Pi readback semantics",
            5: "reference-aligned firmware LED policy flags, default-state initialization, sleep-aware GPIO LED writes, and learned Pi readback semantics",
            6: "reference-aligned GPIO consumer identity, firmware LED policy flags, default-state initialization, sleep-aware GPIO LED writes, and learned Pi readback semantics",
        }[generation]
    else:
        raise ValueError(f"unsupported functional generation: {generation}")

    if generation >= 4:
        state_declaration = "        enum led_default_state default_state;\n"
        state_initialization = '''        default_state = led_init_default_state_get(child);
        if (default_state == LEDS_DEFSTATE_KEEP) {
            state = gpiod_get_value_cansleep(led->gpiod);
            if (state < 0) {
                fwnode_handle_put(child);
                return state;
            }
        } else {
            state = (default_state == LEDS_DEFSTATE_ON);
        }
        dev_info(dev, "AURUM_GEN4_DEFAULT_STATE mode=%d initial=%d\\n", default_state, state);
'''
    else:
        state_declaration = ""
        state_initialization = '''        state = gpiod_get_value_cansleep(led->gpiod);
        if (state < 0) {
            fwnode_handle_put(child);
            return state;
        }
'''

    if generation >= 5:
        policy_setup = '''        if (!fwnode_property_present(child, "retain-state-suspended"))
            led->cdev.flags |= LED_CORE_SUSPENDRESUME;
        if (fwnode_property_present(child, "panic-indicator"))
            led->cdev.flags |= LED_PANIC_INDICATOR;
        if (fwnode_property_present(child, "retain-state-shutdown"))
            led->cdev.flags |= LED_RETAIN_AT_SHUTDOWN;
        fwnode_property_read_string(child, "linux,default-trigger", &led->cdev.default_trigger);
        dev_info(dev,
                 "AURUM_GEN5_POLICY default_trigger=%s suspend_resume=%d panic=%d retain_shutdown=%d\\n",
                 led->cdev.default_trigger ? led->cdev.default_trigger : "none",
                 !!(led->cdev.flags & LED_CORE_SUSPENDRESUME),
                 !!(led->cdev.flags & LED_PANIC_INDICATOR),
                 !!(led->cdev.flags & LED_RETAIN_AT_SHUTDOWN));
'''
    else:
        policy_setup = ""

    if generation >= 6:
        identity_setup = '''        gpiod_set_consumer_name(led->gpiod, led->cdev.dev->kobj.name);
        dev_info(dev, "AURUM_GEN6_CONSUMER_IDENTITY name=%s\\n",
                 led->cdev.dev->kobj.name);
'''
    else:
        identity_setup = ""

    return f'''// Generated by Aurum bounded Pi4 driver synthesis.\n// Generation {generation} implements {capability_comment}.\n#include <linux/container_of.h>\n#include <linux/device.h>\n#include <linux/err.h>\n#include <linux/gpio/consumer.h>\n#include <linux/leds.h>\n#include <linux/mod_devicetable.h>\n#include <linux/module.h>\n#include <linux/platform_device.h>\n#include <linux/property.h>\n#include <linux/slab.h>\n#include <linux/types.h>\n\nstruct aurum_led {{\n    struct led_classdev cdev;\n    struct gpio_desc *gpiod;\n{struct_extra}}};\n\nstruct aurum_leds {{\n    int count;\n    struct aurum_led *leds;\n}};\n\n{set_functions}\nstatic enum led_brightness aurum_led_get(struct led_classdev *cdev)\n{{\n    struct aurum_led *led = container_of(cdev, struct aurum_led, cdev);\n    return gpiod_get_value_cansleep(led->gpiod) ? LED_FULL : LED_OFF;\n}}\n\nstatic int aurum_probe(struct platform_device *pdev)\n{{\n    struct device *dev = &pdev->dev;\n    struct fwnode_handle *child;\n    struct aurum_leds *priv;\n    int count = device_get_child_node_count(dev);\n    int used = 0;\n\n    if (count <= 0)\n        return -ENODEV;\n\n    priv = devm_kzalloc(dev, sizeof(*priv), GFP_KERNEL);\n    if (!priv)\n        return -ENOMEM;\n    priv->leds = devm_kcalloc(dev, count, sizeof(*priv->leds), GFP_KERNEL);\n    if (!priv->leds)\n        return -ENOMEM;\n\n    device_for_each_child_node(dev, child) {{\n        struct aurum_led *led = &priv->leds[used];\n        struct led_init_data init_data = {{ .fwnode = child }};\n{state_declaration}        int state;\n        int ret;\n\n        led->gpiod = devm_fwnode_gpiod_get(dev, child, NULL, GPIOD_ASIS, NULL);\n        if (IS_ERR(led->gpiod)) {{\n            ret = PTR_ERR(led->gpiod);\n            fwnode_handle_put(child);\n            return dev_err_probe(dev, ret, "Aurum could not acquire LED GPIO\\n");\n        }}\n\n{state_initialization}        ret = gpiod_direction_output(led->gpiod, state ? 1 : 0);\n        if (ret) {{\n            fwnode_handle_put(child);\n            return ret;\n        }}\n\n        led->cdev.max_brightness = 1;\n        led->cdev.brightness = state ? 1 : 0;\n{callback_setup}\n        led->cdev.brightness_get = aurum_led_get;\n{policy_setup}        ret = devm_led_classdev_register_ext(dev, &led->cdev, &init_data);\n        if (ret) {{\n            fwnode_handle_put(child);\n            return ret;\n        }}\n{identity_setup}        used++;\n    }}\n\n    priv->count = used;\n    platform_set_drvdata(pdev, priv);\n    dev_info(dev, "Aurum generation-{generation} LED driver active leds=%d\\n", used);\n    return used ? 0 : -ENODEV;\n}}\n\nstatic const struct of_device_id aurum_of_match[] = {{\n    {{ .compatible = "{_c_string(compatible)}" }},\n    {{ }}\n}};\nMODULE_DEVICE_TABLE(of, aurum_of_match);\n\nstatic struct platform_driver aurum_driver = {{\n    .probe = aurum_probe,\n    .driver = {{\n        .name = "{_c_string(driver_name)}",\n        .of_match_table = aurum_of_match,\n    }},\n}};\n\nmodule_platform_driver(aurum_driver);\nMODULE_LICENSE("GPL");\nMODULE_AUTHOR("Aurum");\nMODULE_DESCRIPTION("Aurum Pi4 gpio-leds bounded functional candidate generation {generation}");\n'''


def synthesize(evidence: dict, out_dir: Path, generation: int = 1) -> dict:
    target = str(evidence.get("target", ""))
    if target not in ALLOWED_TARGETS:
        raise ValueError(f"unsupported bounded target: {target}")
    if generation not in {1, 2, 3, 4, 5, 6}:
        raise ValueError(f"unsupported generation: {generation}")
    policy = ALLOWED_TARGETS[target]
    compatible = str(evidence.get("compatible", ""))
    if compatible != policy["compatible"]:
        raise ValueError(f"compatible mismatch: {compatible!r}")
    working_driver = str(evidence.get("working_driver", ""))
    if working_driver not in policy["working_driver_aliases"]:
        raise ValueError(f"unexpected working driver: {working_driver!r}")
    device = str(evidence.get("device", "")).strip()
    kernel = str(evidence.get("kernel", "")).strip()
    model = str(evidence.get("model", "")).strip()
    if not device or not kernel or "Raspberry Pi 4" not in model:
        raise ValueError("incomplete exact-hardware evidence")

    driver_name = policy["candidate_driver"]
    source = (
        _generation_1_source(compatible, driver_name)
        if generation == 1
        else _functional_source(compatible, driver_name, generation)
    )
    module_stem = driver_name.replace("-", "_")
    makefile = f"obj-m += {module_stem}.o\n"

    out_dir.mkdir(parents=True, exist_ok=True)
    source_path = out_dir / f"{module_stem}.c"
    makefile_path = out_dir / "Makefile"
    source_path.write_text(source, encoding="utf-8")
    makefile_path.write_text(makefile, encoding="utf-8")

    digest = hashlib.sha256(source.encode("utf-8")).hexdigest()
    capability = {
        1: "platform-device ownership/probe only",
        2: "bounded GPIO LED on/off plus reference-compatible readback",
        3: "reference-aligned sleep-aware GPIO LED writes plus reference-compatible readback",
        4: "reference-aligned default-state initialization plus sleep-aware GPIO LED writes and reference-compatible readback",
        5: "reference-aligned firmware LED policy flags plus default-state initialization, sleep-aware GPIO LED writes, and reference-compatible readback",
        6: "reference-aligned GPIO consumer identity plus firmware LED policy flags, default-state initialization, sleep-aware GPIO LED writes, and reference-compatible readback",
    }[generation]
    manifest = {
        "schema": SCHEMA,
        "target": target,
        "candidate_driver": driver_name,
        "module_stem": module_stem,
        "compatible": compatible,
        "observed_device": device,
        "observed_kernel": kernel,
        "observed_model": model,
        "observed_working_driver": working_driver,
        "safety_class": policy["safety_class"],
        "generation": generation,
        "capability": capability,
        "physical_led_writes": generation >= 2,
        "gpio_sleep_aware": generation >= 3,
        "default_state_aware": generation >= 4,
        "firmware_policy_aware": generation >= 5,
        "suspend_resume_policy_aware": generation >= 5,
        "panic_indicator_policy_aware": generation >= 5,
        "retain_shutdown_policy_aware": generation >= 5,
        "gpio_consumer_identity_aligned": generation >= 6,
        "raw_mmio_writes": False,
        "firmware_changes": False,
        "network_changes": False,
        "storage_changes": False,
        "source_sha256": digest,
        "rollback_required": True,
    }
    (out_dir / "candidate-manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--evidence", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--generation", type=int, default=1)
    args = parser.parse_args()
    evidence = json.loads(Path(args.evidence).read_text(encoding="utf-8"))
    manifest = synthesize(evidence, Path(args.out), generation=args.generation)
    print(json.dumps(manifest, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
