<?php
declare(strict_types=1);
require __DIR__.'/lib.php'; require __DIR__.'/siri.php'; require __DIR__.'/shortcut.php';
try{
$config=pipeline_load_config();$method=strtoupper((string)($_SERVER['REQUEST_METHOD']??'GET'));$path=(string)(parse_url((string)($_SERVER['REQUEST_URI']??'/'),PHP_URL_PATH)?:'/');
if($method==='GET'&&(str_ends_with($path,'/health')||str_ends_with($path,'/health/'))){$status=pipeline_config_status($config);$status['storage_writable']=pipeline_storage_ready($config);$status['siri_configured']=pipeline_siri_configured($config);$status['shortcut_configured']=pipeline_shortcut_configured($config);$ready=$status['github_configured']&&$status['authentication_configured']&&$status['storage_writable'];pipeline_respond($ready?200:503,array_merge(['status'=>$ready?'ok':'not_ready','service'=>'chat-to-git-webhook','version'=>PIPELINE_VERSION,'route'=>'webhook_to_github'],$status));}
if(!pipeline_storage_ready($config))pipeline_respond(503,['error'=>'storage-unavailable']);
if($method==='POST'&&(str_ends_with($path,'/shortcut/enroll')||str_ends_with($path,'/shortcut/enroll/'))){if(pipeline_shortcut_configured($config))pipeline_respond(409,['error'=>'shortcut-already-enrolled']);if(!pipeline_rate_limit($config))pipeline_respond(429,['error'=>'rate-limit']);$raw=pipeline_raw_body();$input=json_decode($raw,true);if(!is_array($input))pipeline_respond(400,['error'=>'invalid-json']);if(!pipeline_shortcut_enroll($config,$input))pipeline_respond(401,['error'=>'enrollment-rejected']);pipeline_respond(201,['enrolled'=>true,'device_id'=>(string)$input['device_id']]);}
if($method==='POST'&&(str_ends_with($path,'/shortcut/dispatch')||str_ends_with($path,'/shortcut/dispatch/'))){$raw=pipeline_raw_body();$input=json_decode($raw,true);if(!is_array($input))pipeline_respond(400,['error'=>'invalid-json']);if(!pipeline_shortcut_configured($config))pipeline_respond(503,['error'=>'shortcut-ingress-not-configured']);if(!pipeline_shortcut_authenticate($config,$input))pipeline_respond(401,['error'=>'unauthorized']);if(!pipeline_rate_limit($config))pipeline_respond(429,['error'=>'rate-limit']);$request=pipeline_shortcut_request($input,(string)$config['github_repository']);pipeline_dispatch($config,$request);pipeline_audit($config,['request_id'=>$request['request_id'],'event'=>'dispatch','status'=>'accepted','http_status'=>202,'route'=>'shortcut_to_github','github_status'=>204]);pipeline_respond(202,['accepted'=>true,'request_id'=>$request['request_id'],'route'=>'shortcut_to_github','status_path'=>'/chat-to-git/shortcut/status/'.rawurlencode($request['request_id'])]);}
if($method==='GET'&&preg_match('#/shortcut/status/([A-Za-z0-9][A-Za-z0-9._-]{2,63})/?$#',$path,$match)){if(!pipeline_shortcut_configured($config))pipeline_respond(503,['error'=>'shortcut-ingress-not-configured']);$token=pipeline_request_header('X-Shortcut-Token');$device=pipeline_request_header('X-Shortcut-Device-Id');$credentials=pipeline_shortcut_credentials($config);if($token===''||$device===''||!hash_equals((string)$credentials['token'],$token)||!hash_equals((string)$credentials['device_id'],$device))pipeline_respond(401,['error'=>'unauthorized']);if(!pipeline_rate_limit($config))pipeline_respond(429,['error'=>'rate-limit']);$result=pipeline_feedback_status($config,$match[1]);if($result===null)pipeline_respond(404,['error'=>'request-status-not-found']);$result['route']='shortcut_to_github';pipeline_respond(200,$result);}
if($method==='POST'&&(str_ends_with($path,'/siri/challenge')||str_ends_with($path,'/siri/challenge/'))){if(!pipeline_siri_configured($config))pipeline_respond(503,['error'=>'siri-ingress-not-configured']);if(!pipeline_rate_limit($config))pipeline_respond(429,['error'=>'rate-limit']);$raw=pipeline_raw_body();$input=json_decode($raw,true);if(!is_array($input)||!isset($input['device_id'])||!is_string($input['device_id']))pipeline_respond(400,['error'=>'invalid-device']);pipeline_respond(200,pipeline_siri_issue($config,$input['device_id']));}
if($method==='POST'&&(str_ends_with($path,'/siri/dispatch')||str_ends_with($path,'/siri/dispatch/'))){if(!pipeline_siri_configured($config))pipeline_respond(503,['error'=>'siri-ingress-not-configured']);$raw=pipeline_raw_body();if(!pipeline_siri_authenticate($config,$method,$path,$raw))pipeline_respond(401,['error'=>'unauthorized']);if(!pipeline_rate_limit($config))pipeline_respond(429,['error'=>'rate-limit']);$input=json_decode($raw,true);if(!is_array($input))pipeline_respond(400,['error'=>'invalid-json']);$request=pipeline_siri_dispatch_request($input,(string)$config['github_repository']);pipeline_dispatch($config,$request);pipeline_audit($config,['request_id'=>$request['request_id'],'event'=>'dispatch','status'=>'accepted','http_status'=>202,'route'=>'siri_to_github','github_status'=>204]);pipeline_respond(202,['accepted'=>true,'request_id'=>$request['request_id'],'route'=>'siri_to_github','status_path'=>'/chat-to-git/siri/status/'.rawurlencode($request['request_id']),'last_known_good'=>'GitHub runner receipt remains required for success']);}
if($method==='GET'&&preg_match('#/siri/status/([A-Za-z0-9][A-Za-z0-9._-]{2,63})/?$#',$path,$match)){if(!pipeline_siri_configured($config))pipeline_respond(503,['error'=>'siri-ingress-not-configured']);if(!pipeline_siri_authenticate($config,$method,$path,''))pipeline_respond(401,['error'=>'unauthorized']);if(!pipeline_rate_limit($config))pipeline_respond(429,['error'=>'rate-limit']);$result=pipeline_feedback_status($config,$match[1]);if($result===null)pipeline_respond(404,['error'=>'request-status-not-found']);$result['route']='siri_to_github';pipeline_respond(200,$result);}
if($method==='GET'&&preg_match('#/status/([A-Za-z0-9][A-Za-z0-9._-]{2,63})/?$#',$path,$match)){if(!pipeline_authorized($config,''))pipeline_respond(401,['error'=>'unauthorized']);if(!pipeline_rate_limit($config))pipeline_respond(429,['error'=>'rate-limit']);$result=pipeline_feedback_status($config,$match[1]);if($result===null)pipeline_respond(404,['error'=>'request-status-not-found']);pipeline_respond(200,$result);}
if($method!=='POST'||!(str_ends_with($path,'/webhook/voice')||str_ends_with($path,'/webhook/voice/')))pipeline_respond(404,['error'=>'not-found']);
$raw=pipeline_raw_body();if(!pipeline_authorized($config,$raw))pipeline_respond(401,['error'=>'unauthorized']);if(!pipeline_rate_limit($config))pipeline_respond(429,['error'=>'rate-limit']);$input=json_decode($raw,true);if(!is_array($input))pipeline_respond(400,['error'=>'invalid-json']);$request=pipeline_validate_request($input,(string)$config['github_repository']);pipeline_dispatch($config,$request);pipeline_audit($config,['request_id'=>$request['request_id'],'event'=>'dispatch','status'=>'accepted','http_status'=>202,'route'=>'webhook_to_github','github_status'=>204]);pipeline_respond(202,['accepted'=>true,'request_id'=>$request['request_id'],'route'=>'webhook_to_github','status_path'=>'/chat-to-git/status/'.rawurlencode($request['request_id']),'last_known_good'=>'GitHub runner receipt remains required for success']);
}catch(InvalidArgumentException $error){pipeline_respond(400,['error'=>$error->getMessage()]);}catch(Throwable $error){error_log('chat-to-git-webhook: '.$error->getMessage());pipeline_respond(502,['error'=>'upstream-unavailable']);}
