"""Synthesize and verify a non-binding Pi3 LAN9514/smsc95xx candidate core.

This advances the first adaptive-driver milestone from a reference behavior model to
a concrete candidate implementation without touching hardware. The generated C core
contains no kernel/module entry point, no device I/O, no binding path, and no
persistent mutation path. It is compiled and exercised only in a controlled host
process against the sealed functional model.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Any, Mapping

MODEL_SCHEMA = "aurum.pi3.smsc95xx.functional-model.v1"
CANDIDATE_SCHEMA = "aurum.pi3.smsc95xx.nonbinding-candidate.v1"
_REQUIRED_FALSE = (
    "mutation_allowed",
    "driver_binding_change_allowed",
    "kernel_module_load_allowed",
    "firmware_mutation_allowed",
    "network_configuration_change_allowed",
    "promotion_allowed",
    "write_authority",
)


def _canonical_sha256(value: Mapping[str, Any]) -> str:
    return hashlib.sha256(
        json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True, allow_nan=False).encode("utf-8")
    ).hexdigest()


def _verify_sealed(value: Mapping[str, Any]) -> bool:
    claimed = value.get("receipt_sha256")
    if not isinstance(claimed, str):
        return False
    body = dict(value)
    body.pop("receipt_sha256", None)
    return claimed == _canonical_sha256(body)


def _mapping(value: Any, name: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise ValueError(f"{name} must be a mapping")
    return value


def _load(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8-sig"))
    if not isinstance(value, dict):
        raise ValueError(f"expected JSON object: {path}")
    return value


def _parse_usb_id(value: Any, name: str) -> tuple[int, int]:
    text = str(value or "")
    parts = text.split(":")
    if len(parts) != 2 or any(len(part) != 4 for part in parts):
        raise ValueError(f"{name} must be a 4-digit VID:PID pair")
    try:
        return int(parts[0], 16), int(parts[1], 16)
    except ValueError as exc:
        raise ValueError(f"{name} must be hexadecimal") from exc


def synthesize_candidate(functional_model: Mapping[str, Any]) -> tuple[str, dict[str, Any]]:
    if functional_model.get("schema") != MODEL_SCHEMA or not _verify_sealed(functional_model):
        raise ValueError("functional model must be a valid sealed receipt")
    if functional_model.get("state") != "verified-offline-functional-model":
        raise ValueError("functional model is not verified")

    authority = _mapping(functional_model.get("authority"), "functional-model authority")
    if any(authority.get(key) is not False for key in _REQUIRED_FALSE):
        raise ValueError("functional model carries non-zero authority")

    scope = _mapping(functional_model.get("scope"), "functional-model scope")
    if scope.get("protected_reference_driver") != "smsc95xx":
        raise ValueError("functional model is not bound to protected smsc95xx evidence")
    parent_vid, parent_pid = _parse_usb_id(scope.get("usb_parent"), "usb_parent")
    usb_vid, usb_pid = _parse_usb_id(scope.get("usb_ethernet_function"), "usb_ethernet_function")

    speeds = scope.get("link_speeds_mbps")
    duplex_modes = scope.get("duplex_modes")
    if speeds != [10, 100] or duplex_modes != ["half", "full"]:
        raise ValueError("candidate synthesis only supports the proven 10/100 half/full envelope")

    constants = _mapping(functional_model.get("constants"), "functional-model constants")
    defaults = _mapping(functional_model.get("defaults"), "functional-model defaults")
    tx_overhead = int(constants.get("tx_overhead_bytes"))
    tx_overhead_csum = int(constants.get("tx_overhead_checksum_bytes"))
    if (tx_overhead, tx_overhead_csum) != (8, 12):
        raise ValueError("candidate synthesis constants differ from the sealed reference model")
    if defaults.get("rx_checksum_enabled") is not True:
        raise ValueError("candidate synthesis expects the proven RX checksum default")

    source = f'''/* Generated by Aurum from a sealed non-actuating LAN9514/smsc95xx model.
 * NON-BINDING SHADOW CANDIDATE: no device I/O, kernel/module entry point, DMA,
 * firmware, EEPROM, network configuration, or persistent mutation path exists.
 */
#include <stddef.h>
#include <stdint.h>

#define AURUM_PARENT_VID 0x{parent_vid:04x}u
#define AURUM_PARENT_PID 0x{parent_pid:04x}u
#define AURUM_USB_VID 0x{usb_vid:04x}u
#define AURUM_USB_PID 0x{usb_pid:04x}u
#define AURUM_TX_OVERHEAD {tx_overhead}u
#define AURUM_TX_OVERHEAD_CSUM {tx_overhead_csum}u

typedef struct {{
    int identity_verified;
    int carrier;
    unsigned speed_mbps;
    int full_duplex;
    int rx_checksum_enabled;
}} aurum_smsc95xx_state;

int aurum_smsc95xx_init(aurum_smsc95xx_state *state,
                        uint16_t parent_vid, uint16_t parent_pid,
                        uint16_t usb_vid, uint16_t usb_pid) {{
    if (!state) return -1;
    if (parent_vid != AURUM_PARENT_VID || parent_pid != AURUM_PARENT_PID ||
        usb_vid != AURUM_USB_VID || usb_pid != AURUM_USB_PID) return -2;
    state->identity_verified = 1;
    state->carrier = 0;
    state->speed_mbps = 0;
    state->full_duplex = 0;
    state->rx_checksum_enabled = 1;
    return 0;
}}

int aurum_smsc95xx_set_link(aurum_smsc95xx_state *state, int carrier,
                            unsigned speed_mbps, int full_duplex) {{
    if (!state || !state->identity_verified) return -1;
    if (!carrier) {{
        state->carrier = 0;
        state->speed_mbps = 0;
        state->full_duplex = 0;
        return 0;
    }}
    if (speed_mbps != 10u && speed_mbps != 100u) return -2;
    if (full_duplex != 0 && full_duplex != 1) return -3;
    state->carrier = 1;
    state->speed_mbps = speed_mbps;
    state->full_duplex = full_duplex;
    return 0;
}}

int aurum_smsc95xx_set_rx_checksum(aurum_smsc95xx_state *state, int enabled) {{
    if (!state || !state->identity_verified) return -1;
    if (enabled != 0 && enabled != 1) return -2;
    state->rx_checksum_enabled = enabled;
    return 0;
}}

size_t aurum_smsc95xx_tx_frame_len(const aurum_smsc95xx_state *state,
                                   size_t payload_len, int checksum_partial) {{
    if (!state || !state->identity_verified || !state->carrier) return 0u;
    if (checksum_partial != 0 && checksum_partial != 1) return 0u;
    return payload_len + (checksum_partial ? AURUM_TX_OVERHEAD_CSUM : AURUM_TX_OVERHEAD);
}}
'''

    source_sha = hashlib.sha256(source.encode("utf-8")).hexdigest()
    receipt: dict[str, Any] = {
        "schema": CANDIDATE_SCHEMA,
        "state": "synthesized-nonbinding-shadow-candidate",
        "candidate_kind": "portable-c-shadow-driver-core",
        "input_functional_model_receipt_sha256": functional_model.get("receipt_sha256"),
        "source_sha256": source_sha,
        "scope": {
            "controller": scope.get("controller"),
            "usb_parent": scope.get("usb_parent"),
            "usb_ethernet_function": scope.get("usb_ethernet_function"),
            "link_speeds_mbps": [10, 100],
            "duplex_modes": ["half", "full"],
            "rx_checksum_control": True,
            "tx_framing_overhead_bytes": [8, 12],
        },
        "authority": {key: False for key in _REQUIRED_FALSE},
        "invariants": {
            "live_pi_contacted": False,
            "device_io_performed": False,
            "kernel_module_entrypoint_present": False,
            "driver_binding_path_present": False,
            "firmware_or_eeprom_path_present": False,
            "network_configuration_path_present": False,
            "last_known_good_preserved": True,
            "mutation_authority_granted": False,
            "promotion_authority_granted": False,
        },
        "next_gate": "controlled-candidate-vs-functional-model-differential-verification",
        "strongest_claim": (
            "Aurum synthesized a concrete portable C shadow candidate from the sealed LAN9514/smsc95xx functional model. "
            "The candidate can reproduce the bounded identity, 10/100 link, RX checksum, and TX framing behaviors in a host process, "
            "but it is not a kernel driver, is not bindable, and carries no mutation or promotion authority."
        ),
    }
    receipt["receipt_sha256"] = _canonical_sha256(receipt)
    return source, receipt


def verify_candidate_source(source: str, receipt: Mapping[str, Any], cc: str | None = None) -> dict[str, Any]:
    if receipt.get("schema") != CANDIDATE_SCHEMA or not _verify_sealed(receipt):
        raise ValueError("candidate receipt is not sealed")
    if hashlib.sha256(source.encode("utf-8")).hexdigest() != receipt.get("source_sha256"):
        raise ValueError("candidate source hash does not match sealed receipt")
    forbidden_tokens = (
        "module_init",
        "usb_register",
        "usb_driver",
        "request_firmware",
        "ioremap",
        "writel(",
        "readl(",
        "netdev_ops",
        "ethtool_ops",
    )
    found = [token for token in forbidden_tokens if token in source]
    if found:
        raise ValueError("non-binding candidate contains forbidden actuation tokens: " + ", ".join(found))

    compiler = cc or shutil.which("cc") or shutil.which("gcc") or shutil.which("clang")
    if not compiler:
        raise RuntimeError("no C compiler available for controlled candidate verification")

    harness = r'''
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "candidate.c"
int main(void) {
    aurum_smsc95xx_state s = {0};
    if (aurum_smsc95xx_init(&s, 0x0424, 0x9514, 0x0424, 0xec00) != 0) return 10;
    if (aurum_smsc95xx_set_link(&s, 1, 100, 1) != 0) return 11;
    if (aurum_smsc95xx_set_rx_checksum(&s, 0) != 0 || s.rx_checksum_enabled != 0) return 12;
    if (aurum_smsc95xx_set_rx_checksum(&s, 1) != 0 || s.rx_checksum_enabled != 1) return 13;
    if (aurum_smsc95xx_tx_frame_len(&s, 1500, 0) != 1508) return 14;
    if (aurum_smsc95xx_tx_frame_len(&s, 1500, 1) != 1512) return 15;
    if (aurum_smsc95xx_set_link(&s, 1, 1000, 1) == 0) return 16;
    aurum_smsc95xx_state bad = {0};
    if (aurum_smsc95xx_init(&bad, 0x0424, 0x9514, 0x0424, 0x7800) == 0) return 17;
    printf("AURUM_PI3_SMSC95XX_CANDIDATE_OK\n");
    return 0;
}
'''
    with tempfile.TemporaryDirectory(prefix="aurum-smsc95xx-") as temp_dir:
        root = Path(temp_dir)
        (root / "candidate.c").write_text(source, encoding="utf-8")
        (root / "harness.c").write_text(harness, encoding="utf-8")
        binary = root / "candidate-test"
        build = subprocess.run(
            [compiler, "-std=c11", "-Wall", "-Wextra", "-Werror", str(root / "harness.c"), "-o", str(binary)],
            text=True,
            capture_output=True,
            check=False,
        )
        if build.returncode != 0:
            raise RuntimeError("candidate compilation failed:\n" + build.stdout + build.stderr)
        run = subprocess.run([str(binary)], text=True, capture_output=True, check=False)
        if run.returncode != 0 or "AURUM_PI3_SMSC95XX_CANDIDATE_OK" not in run.stdout:
            raise RuntimeError("candidate controlled verification failed:\n" + run.stdout + run.stderr)

    return {
        "compiled": True,
        "controlled_harness_passed": True,
        "wrong_controller_rejected": True,
        "unproven_gigabit_rejected": True,
        "rx_checksum_sequence_reproduced": True,
        "tx_framing_reproduced": True,
        "device_io_performed": False,
        "binding_attempted": False,
        "mutation_authority_granted": False,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", required=True, type=Path)
    parser.add_argument("--source-output", required=True, type=Path)
    parser.add_argument("--receipt-output", required=True, type=Path)
    parser.add_argument("--cc")
    args = parser.parse_args()

    source, receipt = synthesize_candidate(_load(args.model))
    verification = verify_candidate_source(source, receipt, args.cc)
    final = dict(receipt)
    final["verification"] = verification
    final.pop("receipt_sha256", None)
    final["state"] = "verified-nonbinding-shadow-candidate"
    final["next_gate"] = "differential-candidate-vs-functional-model-scenario-suite"
    final["receipt_sha256"] = _canonical_sha256(final)

    args.source_output.parent.mkdir(parents=True, exist_ok=True)
    args.receipt_output.parent.mkdir(parents=True, exist_ok=True)
    args.source_output.write_text(source, encoding="utf-8")
    args.receipt_output.write_text(json.dumps(final, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print("AURUM_PI3_SMSC95XX_NONBINDING_CANDIDATE_OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
